export { default as ArrowLeft } from '/icons/arrow-left-solid.svg';
export { default as Clock } from '/icons/clock-regular.svg';
export { default as Envelope } from '/icons/envelope-regular.svg';
export { default as MagnifyingGlass } from '/icons/magnifying-glass-solid.svg';
export { default as Pencil } from '/icons/pencil-solid.svg';
export { default as Plus } from '/icons/plus-solid.svg';
export { default as Upload } from '/icons/upload-solid.svg';
export { default as UserGroup } from '/icons/user-group-solid.svg';
export { default as Xmark } from '/icons/xmark-solid.svg';
